### ISSUE TITLE
Can pyDRTtools handles the inductive loops in EIS

### ISSUE THREAD

**Issue by jianzuo** [ciuccislab/pyDRTtools#12]
In fuel cells, usually, there are inductive loops in the lower and higher frequency range, such as in 
[check_mea.csv](https://github.com/ciuccislab/pyDRTtools/files/14180221/check_mea.csv)
.
I noticed that pyDRTtools provides an option with inductive included. Does this mean 
that both inductive loops in the above EIS can be handled? 
From the results, it seems that the inductive loop in the low-frequency range is not included.

**Comment by ciuccislab** [comment]
Hello, 

The inductive loop where DRT can be negative is not possible here, as pyDRTtools enforces non-negativity constraint, and the obtained DRT values are positive everywhere. Nontheless, you can use other DRT framework in our GitHub channel to handle a case where DRT can be negative (https://github.com/ciuccislab/DNN-DRT).

![image](https://github.com/ciuccislab/pyDRTtools/assets/57649983/23b43d18-ec39-48d8-ac6b-9c041d0345cb)

We are current preparing a new interface for pyDRTtools that will include this functionality.

**Comment by jianzuo** [comment]
Hi,
Thank you very much for the reply. 
Looking forward to the future release, thank you!
