### ISSUE TITLE
How to obtain the ECM element parameters?

### ISSUE THREAD

**Issue by jianzuo** [ciuccislab/pyDRTtools#13]
Hello,
The pyDRTtool supports exporting the fitted EIS curve, can you please help to also export the 
ECM element values that produce the fitted EIS curve?

Thank you!

**Comment by ciuccislab** [comment]
Hello,

Do you mean the recovered impedance that fit the data? You can actually get fit for your data. Just export EIS results to see recovered impedance for your EIS plot.

**Comment by jianzuo** [comment]
Thank you for the reply.
For the fitted EIS curve, it is obtained by fitting a series of Resistor (R) and constant phase element (CPE) in parallel, right?
I mean to provide the values of those Rs and CPEs. 
Thank you!

**Comment by ciuccislab** [comment]
Hello, 

Thank you for your interest in pyDRTtools.

Okay, you want to fit equivalent circuit model (ECM) and obtain values for the ECM parameter. We are currently updating the interface to enable ECM fitting. The subsequent version of the user interface will have button for ECM fitting. 

Thank you.

**Comment by jianzuo** [comment]
That would be great, looking forward to the next release of the library.

Actually, what I am searching here is to present the supporting results for the 'recovered impedance' as you have said before.
In the current version, I assume that this recovered impedance is obtained by fitting an equivalent circuit, right? 
If yes, is it possible to export relevant ECM parameters?
If not, is there an explanation of how the recovered impedance is obtained?

Thank you very much for your time!

**Comment by ciuccislab** [comment]
Hello,
Thank you for your interest in pyDRTtools. The impedance is obtained from the recovered DRT, i.e., by multiplying the recovered DRT with the discretization matrix. Z_recovered = Ax (where x is the recovered DRT)

**Comment by ciuccislab** [comment]
![image](https://github.com/ciuccislab/pyDRTtools/assets/57649983/ad8a27d2-687e-4eb2-81bd-51db3cd82056)


This code snippet shows how the real and imaginary impedance components are recovered.

**Comment by jianzuo** [comment]
Thank you very much for the reply. It is clear now, I will check this part of the code to understand this.

**Comment by yuepeng-zhejiang** [comment]
hello sir :
 when I use the DRTtools to transfor the experimental EIS data to DRT date, how can I only use the transfored DRT date to simulate the ECM  models?(what I need is the simulatied Rp value)
I was tried to intergate the  γ(logτ) dlogτ  from logτ1 to logτ2 to get every peak value.The intergated peak value dont mean the Rp value.

**Comment by ciuccislab** [comment]
Hello there, thanks for your interest. It is very difficult for us to help without seeing your data or the specific problem you have. As we are now in the middle of upgrading pyDRTtools, can you please send us an email to our email addresses with more specifics?
