### ISSUE TITLE
 Bug report：When I use Simple_ run to process my own EIS data, a error occurs because it does not meet the rank requirements of cvxpy

### ISSUE THREAD

**Issue by xhxlab** [ciuccislab/pyDRTtools#2]
When I use this EIS data, and use Simple_run to get DRT, the program reports an error: 
`ValueError: Rank(A) < p or Rank([P; A; G]) < n`
I would like to ask how to solve this problem?
[EIS.csv](https://github.com/ciuccislab/pyDRTtools/files/10146536/EIS.csv)

**Comment by ciuccislab** [comment]
Thank you for reporting the issue you encountered while using pyDRTtools. This issue has been resolved in the current pyDRTtools version on GitHub. The attached EIS data above has been analyzed with the current pyDRTtools version on GitHUb.

![DRT_EIS](https://github.com/ciuccislab/pyDRTtools/assets/57649983/affd3c3f-b149-4365-9652-8d62276a18b1)

**Comment by ciuccislab** [comment]
new version released
