### ISSUE TITLE
Please provide package version requirements.

### ISSUE THREAD

**Issue by EliasGaliounas** [ciuccislab/pyDRTtools#3]
Please provide the versions of Python, Numpy, setup tools etc that your code was written on. Currently any user trying to use the code struggles to establish version compatibility. An easy way to resolve this would be to provide an environment.yml file which users can use to create a conda environment identical to the one you used during development.

**Comment by ciuccislab** [comment]
Thank you for reporting the issue you encountered while using pyDRTtools. We have included the "requirement.txt" in pyDRTtools folder, as recommended. You can check the current version on GitHub. Nonetheless, we are working on new version that will be released soon.

**Comment by ciuccislab** [comment]
new version released
