### ISSUE TITLE
Bug in compute_epsilon?

### ISSUE THREAD

**Issue by hjelmj** [ciuccislab/pyDRTtools#4]
Hi, thanks for a great tool. I am trying out the python version and when I load your .csv sample data into the Python GUI and then try to run the DRT calculation using "Simple Run" or "Baysian Run" run I get the following error: 

pyDRTtools/main/general_fun_v8.py", line 106, in compute_epsilon
    return epsilon[0]
TypeError: 'float' object is not subscriptable
[1]    94298 abort      python pyDRTtools.py

**Comment by ciuccislab** [comment]
Thank you for reporting the issue you encountered while using pyDRTtools, including the error message. The issue with "compute_epsilon" function has already been resolved in the current version on GitHub. Nonetheless, we are working on new version that will be released soon.

**Comment by ciuccislab** [comment]
new version released
