### ISSUE TITLE
Error occur with QuadForm from CVXPY package, please advice what caused this error and how I may by-pass this error. 

### ISSUE THREAD

**Issue by Roy027** [ciuccislab/pyDRTtools#6]
An error occurred: Problem does not follow DCP rules. Specifically:
The objective is not DCP. Its following subexpressions are not:
QuadForm(var46, [[ 2.11547255e+14  0.00000000e+00 -8.36769832e+06 ... -1.12997877e+01
  -8.95461504e+00 -7.09365308e+00]
 [ 0.00000000e+00  1.40000000e+02  6.12591418e+01 ...  1.77243291e-01
   1.13027626e-01  7.16346157e-02]
 [-8.36769832e+06  6.12591418e+01  3.04355041e+01 ...  8.81551655e-02
   5.62171181e-02  3.56299003e-02]
 ...
 [-1.12997877e+01  1.77243291e-01  8.81551655e-02 ...  9.38354421e-02
   6.96569765e-02  4.98352628e-02]
 [-8.95461504e+00  1.13027626e-01  5.62171181e-02 ...  6.96569765e-02
   6.30405086e-02  4.49793980e-02]
 [-7.09365308e+00  7.16346157e-02  3.56299003e-02 ...  4.98352628e-02
   4.49793980e-02  4.32107829e-02]])

**Comment by ciuccislab** [comment]
Thank you for reporting the issue you encountered while using pyDRTtools, including the error message. We are working on new version that will be released soon.

**Comment by ciuccislab** [comment]
new version released
