### ISSUE TITLE
question on how to properly use the DRTtool?

### ISSUE THREAD

**Issue by jianzuo** [ciuccislab/pyDRTtools#9]
Hi,
Thanks for sharing the awesome DRT tool.
I have tried to test the DRT calculation for a simple two resistor-capacitor in series circuit: (R1-C1)-(R2-C2),
where R1=R2=100, C1=1e-3, C2=2C1. 
I tried to compute the DRT for the EIS response from this circuit, data can be found in 
[rq_test2rq.csv](https://github.com/ciuccislab/pyDRTtools/files/13946911/rq_test2rq.csv)

There is only one peak in the obtained results, and the peak results seem not to change with different regularization parameters.
![drtc](https://github.com/ciuccislab/pyDRTtools/assets/39144149/99f50638-a740-4ffc-a524-721508ba8e78)

Can you give some hints on how to obtain the DRT results correctly? 
Thank you!

**Comment by ciuccislab** [comment]
DRTtools/pyDRTtools have different functionalities to optimize drt results. You can choose different discretization methods combined with different regularization methods to optimize results.

I will analyze the data you attached and get back to you

**Comment by jianzuo** [comment]
Hi,
Thank you very much for the help!
I am sorry there is an error in the original data (rq_test2rq.csv) when I created it, I have updated
it in the initial post as well as the DRT results.

It can be seen that the two peaks can not be recognized. I have tried to increase the distance of two peaks, for instance C2=6C1, then the two peaks can be identified. During this process, it seems that varying the regularization parameter (lambda) did not change the DRT results. This seems strange because in the literature (also said in the manual), usually, the resolution of the peaks increases with the decreases of lambda.

Another problem is how can we directly obtain the peak values from the GUI app?

**Comment by thwan** [comment]
We have recently implemented the cross validation function to the pyDRTtools, which allows optimization of the regularization parameter. Nonetheless, we note that some users may want to experiment with their own regularization parameter. In this regard, we have added an extra "custom" option in regularization method. (Please check the latest version). To select your own regularization parameter, you can simply select the "custom" option in regularization method and edit the regularization number prior running.

I hope this can answer your issue.

**Comment by jianzuo** [comment]
Hi,
Thank you very much for the update, I have checked the updated version. Now I see the custome button and see the difference when applying different lambda. My remaining problems are:
1. But after some experiment with the current version of the tool, I think the choice of different regularization methods provided in the GUI seems to be the same? For example, I fixed a regularization parameter, then the DRT results are the same for all provided methods.

2. How do we selected the automated selected regularization parameter as you mentioned, and how do we know which number is being selected as the optimal one?

**Comment by ciuccislab** [comment]
Hello,

1) if you want to insert your own regularization parameter (may be based on your prior experience), you can use "custom" approach as already explained by Dr. Hei above. 

Also, I investigated if the results are the same, I tried higher lambda values then I got different DRT plots. May be you can try values not so close to one another just to confirm.

2) the regularization methods help to automatically select the optimal lambda without the need to insert them yourself. Those methods such as cross-validations and L-curve can handle optimal parameter selection. You just need to choose one of them.

Thank you for your interest in pyDRTtools. Please do let us know if this has resolved the issues. Thank you

**Comment by jianzuo** [comment]
Hello,
Thanks for the reply, this app is really useful, and thanks for making it open-source so that I can use it for my project.

Sorry, I did not make it clear. For point 1, yes, now there is no problem with inserting user-defined regularization parameters. Rather, my question is on the functions provided in the 'Regularization Method' panel, different methods are provided, such as GCV, mGCV and custom, what confused me is that **for the same 'regularization parameter', switching between different methods gives the same DRT plots, is this normal**?

For point 2, sorry I did not see **how to set in the GUI panel to do 'cross-validations' and 'L-curve'**, can you please show specific settings with a photo? Thank you very much! And, if the regularization parameter is being optimized by 'cross-validations' and 'L-curve' methods, **how do I know the value of the optimized regularization parameter** in computing the DRT plot?

**Comment by ciuccislab** [comment]
For cross validations, you can choose any of the following: GCV,  mGCV, rGCV.

![image](https://github.com/ciuccislab/pyDRTtools/assets/57649983/5ec41391-0d12-4cd8-b681-1adb63e3e969)

The optimal regularization parameter will automatically save with the DRT results. You can export DRT results, save the results. When you open the csv file. You will see the regularization parameter, alongside R and L:

![image](https://github.com/ciuccislab/pyDRTtools/assets/57649983/d9a1030f-01d7-4c22-af84-88aa435fcac4)

**Comment by ciuccislab** [comment]
Also, re-im (real-imaginary) and kf (kFold) are part of cross validation methods while LC is the L-curve method.  We abbreviated them.

**Comment by jianzuo** [comment]
Thank you very much for the detailed explanation, now it is clear for me to test these functions.

**Comment by jianzuo** [comment]
I have an extra problem with interpreting the DRT results (not an issue related to this software). 
Taking a simple circuit resistor R and capacitor C in parallel connected, R=200 ohm, C=0.001 F. Then we can use the generated EIS data to compete DRT curve: 
![drtcheck](https://github.com/ciuccislab/pyDRTtools/assets/39144149/0244ee2d-fedc-4254-a53b-48fd7c6cf663)
. 

My question is: What information can we obtain from the DRT results? 

- For example, we can obtain the characteristic time constant (from the peak value of the x-axis), tau=RC. What is the peak value of the Y-axis mean? 
- Can we rely on DRT results to obtain the original values of R and C?

Thank you very much!

**Comment by jianzuo** [comment]
> For cross validations, you can choose any of the following: GCV, mGCV, rGCV.
> 
> ![image](https://private-user-images.githubusercontent.com/57649983/298811476-5ec41391-0d12-4cd8-b681-1adb63e3e969.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjAyOTQsIm5iZiI6MTcwNjAxOTk5NCwicGF0aCI6Ii81NzY0OTk4My8yOTg4MTE0NzYtNWVjNDEzOTEtMGQxMi00Y2Q4LWI2ODEtMWFkYjYzZTNlOTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE0MjYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZTViOGM2NjI3NGUyNmVhMDVjNWRmNTk3MmJjOGUwN2U0NDI0NWE4NjUyOTA1MDRiN2I1YmM5YzEwN2MwMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WVq3Ok-QX5xOHxdQaAUcxcYvgdpUcXUqBjfX6yblP_k)
> 
> The optimal regularization parameter will automatically save with the DRT results. You can export DRT results, save the results. When you open the csv file. You will see the regularization parameter, alongside R and L:
> 
> ![image](https://private-user-images.githubusercontent.com/57649983/298813309-d9a1030f-01d7-4c22-af84-88aa435fcac4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjAyOTQsIm5iZiI6MTcwNjAxOTk5NCwicGF0aCI6Ii81NzY0OTk4My8yOTg4MTMzMDktZDlhMTAzMGYtMDFkNy00YzIyLWFmODQtODhhYTQzNWZjYWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE0MjYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxZmY4NjExY2I0YzY1ODZmNWJlMTFmYTYxNzkwMDc1NDc3OTJhNzE4YzMyYjNjYzE0OTdhZjEzYjFlM2E5YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LmDGLQrwc2mBjZWF_Cxf0ZpvA6vE7E5fs_xiJNM8m8U)

After some experimenting, I found a strange phenomenon regarding above response:
- What you said for the regularization works for the generated circuit (R//C, for example),
- But when testing on a measured EIS 
[check_mea.csv](https://github.com/ciuccislab/pyDRTtools/files/14025450/check_mea.csv)
, the exported regularization parameters (using the methods GCV, mGCV, etc.) are always the same as I inputted in the GUI panel (seems not been optimized for 'complex EIS spectrum'?):
![drt_self](https://github.com/ciuccislab/pyDRTtools/assets/39144149/c74a62df-fb4f-4e1c-a0e5-045c06952697)

**Comment by jianzuo** [comment]
Regarding the results obtained from pyDRT, how do we know **the fitted ECM parameters**?

I checked the exported CSV data file, there are only frequency, real and imagine parts of EIS.
It might be useful to have the estimated ECM parameters (the ECM used to generate the fitted EIS contains inductance, resistance and CPE?). 

Thank you for checking this!
